### ISSUE TITLE
no git issue

### ISSUE THREAD

**Issue by jonathan-annett** [shingolavine/raspberrypimining#2]
here's a quick rewrite to sort out the "no git" issue. (need to have git BEFORE attempting to clone)
----snip-----
#!/bin/bash
if [ "$EUID" -ne 0 ]
        then echo "Please run as root"
else
apt-get update -y
git --version || apt-get install git -y
git clone https://github.com/lucasjones/cpuminer-multi.git
cd cpuminer-multi
apt-get install autoconf -y
apt-get install libcurl4-openssl-dev -y
apt-get install libjansson-dev -y
apt-get install openssl -y
apt-get install libssl-dev -y
./autogen.sh #
./configure
make
printf "To use type ./minerd with any options you want while in the cpuminer-multi folder\n"
printf "For example ./minerd -a cryptonight -o stratum+tcp://fcn-xmr.pool.minergate.com:45590 -u joebob@saintly.com -p x -t 4"

fi
----snip-----

**Comment by 12qusd** [comment]
Haha you're right. I didn't pay attention to where I put it. It should be fixed now for real now
