### ISSUE TITLE
git clone as sudo not allowed

### ISSUE THREAD

**Issue by stofakiller** [shingolavine/raspberrypimining#7]
Hi,

your script gives an error when cloning as sudo...

**Comment by 12qusd** [comment]
Not sure what you mean? Need more detail

**Comment by DIESLTEK710** [comment]
Has this issue been resolved? Is this script still current?

**Comment by 12qusd** [comment]
I've never been able to recreate this issue. It may be an issue with the individual's setup. If someone has a solution they can propose it.
